application/urls.py
from django.urls import path
from application.views import DeviceListView
from application.views import ProductListView
from application.views import OrderFormView
from application.views import OrderProductDeleteView
from application.views import OrderSubmitted
from application.views import OrdersListView
from application.views import OrderDetailView
from application.views import OrderProductCreateUpdate, OrderProductDelete


app_name='application'
urlpatterns = [
    path('', DeviceListView.as_view(), name='DeviceListView'),
    path('<device_id>/product/', ProductListView.as_view(), name='ProductListView'),
    path('OrderProductCreateUpdate/<productid>/', OrderProductCreateUpdate, name='OrderProductCreateUpdate'),
    path('OrderProductDelete/<orderproductid>/', OrderProductDelete, name='OrderProductDelete'),
    path('cart/', OrderFormView.as_view(), name='OrderFormView'),
    path('<order_id>/submitted/', OrderSubmitted, name='OrderSubmitted'),
    path('<product_id>/orderproductdeleteproduct/', OrderProductDeleteView.as_view(), name='OrderProductDeleteView'),
    path('orders/', OrdersListView.as_view(), name='OrdersListView'),
    path('order/<pk>/', OrderDetailView.as_view(), name='OrderDetailView'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from .views import register, activate, profile, password, resendlink


urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='home.html'), name='logout'),
    
    path('register/', register, name='register'),
    path('resendlink/', resendlink, name='resendlink'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('profile/', profile, name='profile'),
    path('password/', password, name='password'),
    
    path('password-reset/', 
        PasswordResetView.as_view(template_name='password_reset.html'),
        name='password_reset'),
    path('password-reset/done/',
        PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
]

templates/alert.html
{% extends 'base.html' %}
{% block content %}
{{ alert }}
<script>
    alert('{{ alert }}'.replaceAll('&amp;', '&'));
</script>
{% endblock content %}

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static '/images/favicon.ico' %}">

    <link rel="stylesheet" href="{% static '/styles/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static '/styles/bootstrap.css' %}">
    
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css"> -->

    <link rel="stylesheet" href="{% static '/styles/style.css' %}">
    
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> -->
    <title>{{ templateName }}</title>    
</head>
<body id="bodybase">
    {% include 'navbar.html' %}
    <br>
    <div class="container-fluid">
        {% include 'messages.html' %}
        {% block content %}
        {% endblock content %}
    </div>    
    {% include 'modal.html' %}
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/htmx.org@1.8.5"
        integrity="sha384-7aHh9lqPYGYZ7sTHvzP1t3BAfLhYSTy9ArHdP3Xsr9/3TlGurYgcPBoFmXX2TX/w" crossorigin="anonymous"></script> -->

    <script src="{% static '/scripts/bootstrap.bundle.js' %}"></script>
    <script src="{% static '/scripts/jquery.js' %}"></script>
    <script src="{% static '/scripts/htmx.min.js' %}"></script>
    <script src="{% static '/scripts/htmx.js' %}"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
    <ul>
        {% for brand in brand_object_list %}
            <li>{{ brand.name }}</li>
        {% endfor %}
    </ul>
{% else %}
    <h3 class="text-danger">Please Login before testing</h3>
{% endif %}
{% endblock content %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

templates/modal.html
<div class="modal fade" id="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1">
    <div class="modal-dialog modal-dialog-scrollable modal-xl" id="dialog" hx-target="this">
    </div>
</div>

templates/navbar.html
{% load static %}<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <span class="navbar-brand" style="color:steelblue;">
            <img src="{% static '/images/favicon.ico' %}" width="24" height="24">
            {{ templateName }}
        </span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <!-- <a class="nav-link active" aria-current="page" href="%}{% url 'home' ">Home</a> -->
                    <a class="nav-link active" aria-current="page" href="{% url 'application:DeviceListView' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'application:DeviceListView' %}">List of Devices</a>
                </li>
                {% if user.is_authenticated %}
                    <!-- <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Setup
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="%}{% url 'familys:ListView' ">List of Families</a></li>
                            <li><a class="dropdown-item" href="%}{% url 'persons:ListView' ">List of Persons</a></li>
                        </ul>
                    </li> -->
                {% endif %}
            </ul>
            <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item mt-1 mx-2">
                    {% if user.is_authenticated %}
                        <span class="text-info fs-5">
                            Logged as 
                                <span class="text-danger">
                                    {% if request.user.first_name %}
                                        ({{ request.user.first_name|title }} {{ request.user.last_name|title }})
                                    {% else %}
                                        ({{ request.user|title }})
                                    {% endif %}
                                </span>
                        </span>
                    {% endif %}
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'application:OrderFormView' %}">View Cart</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown">My Account</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'application:OrdersListView' %}">List of Orders</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'userprofile' %}">Profile</a></li>
                            <!-- <li><a class="dropdown-item" href="%}{% url 'profile' ">Profile</a></li> -->
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'password' %}">Password</a></li>
                        </ul>
                    </li>                
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userregister' %}">Register</a>
                        <!-- <a class="nav-link" href="%}{% url 'register' ">Register</a> -->
                    </li>
                {% endif %}
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/nothing.html
{% extends 'base.html' %}
{% block content %}
{% endblock content %}

templates/pdflist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style type="text/css">
        /* Style the header: fixed position (always stay at the top) */
        .header {
            position: fixed;
            top: 5;
            margin-top: 5px;
            z-index: 1;
            text-align: center;
            vertical-align: text-bottom;
            padding-top: 10px;
            width: 100%;
            background-color: #f1f1f1;
            font-size:xx-large;
        }
  
        .content {
            margin-top: 5px;
            font-size: larger;
            text-align: center;
            text-emphasis-color: red;
        }
    </style>
</head>
<body>
    <div class="header">
        List of Person
    </div>
    <div class="content">
        <table>
            {% for object in object_list %}
                <tr>
                    <td>{{ object.name }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td>No records found !!!</td>
                </tr>
            {% endfor %}
        </table>
    </div>    
</body>
</html>