application/urls.py
from django.urls import path
from application.views import DeviceListView
from application.views import ProductListView
from application.views import OrderFormView
from application.views import OrderProductDeleteView
from application.views import OrderSubmitted
from application.views import OrdersListView
from application.views import OrderDetailView
from application.views import OrderProductCreateUpdate, OrderProductDelete


app_name='application'
urlpatterns = [
    path('', DeviceListView.as_view(), name='DeviceListView'),
    path('<device_id>/product/', ProductListView.as_view(), name='ProductListView'),
    path('OrderProductCreateUpdate/<productid>/', OrderProductCreateUpdate, name='OrderProductCreateUpdate'),
    path('OrderProductDelete/<orderproductid>/', OrderProductDelete, name='OrderProductDelete'),
    path('cart/', OrderFormView.as_view(), name='OrderFormView'),
    path('<order_id>/submitted/', OrderSubmitted, name='OrderSubmitted'),
    path('<product_id>/orderproductdeleteproduct/', OrderProductDeleteView.as_view(), name='OrderProductDeleteView'),
    path('orders/', OrdersListView.as_view(), name='OrdersListView'),
    path('order/<pk>/', OrderDetailView.as_view(), name='OrderDetailView'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from .views import register, activate, profile, password, resendlink


urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='home.html'), name='logout'),
    
    path('register/', register, name='register'),
    path('resendlink/', resendlink, name='resendlink'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('profile/', profile, name='profile'),
    path('password/', password, name='password'),
    
    path('password-reset/', 
        PasswordResetView.as_view(template_name='password_reset.html'),
        name='password_reset'),
    path('password-reset/done/',
        PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
]

application/models.py
from crum import get_current_user
from django.db import models
from django.db.models.signals import pre_save
from django.conf import settings


class Category(models.Model):
    data = models.CharField(max_length=50, unique=True, editable=False)
    name = models.CharField(max_length=50, unique=True, verbose_name='Category Name', help_text='Enter Category Name')
    active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name


class Brand(models.Model):
    data = models.CharField(max_length=50, unique=True, editable=False)
    name = models.CharField(max_length=50, unique=True, verbose_name='Brand Name', help_text='Enter Brand Name')
    isnotpopular = models.BooleanField(default=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Device(models.Model):
    code = models.CharField(max_length=20)
    data = models.CharField(max_length=50, unique=True, editable=False)
    name = models.CharField(max_length=50, unique=True, verbose_name='Device Name', help_text='Enter Device Name')
    active = models.BooleanField(default=True)
    brand = models.ForeignKey(Brand, on_delete=models.RESTRICT)

    def __str__(self):
        return self.name   


from os import path
def upload_to(instance, filename):
    return path.join(instance.device.code, filename)

class Product(models.Model):
    sku = models.CharField(max_length=50, unique=True, editable=False)
    title = models.CharField(max_length=255, editable=False)
    stock = models.SmallIntegerField(default=0)
    cost = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    price = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    code = models.CharField(max_length=15, null=True, blank=True, editable=False)
    device = models.ForeignKey(Device, on_delete=models.RESTRICT)
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    image = models.ImageField(
        max_length=250, upload_to=upload_to,
        null=True, blank=True, editable=False,
        verbose_name='Product Image', help_text='Select image file to upload'
    )

    class Meta:
        ordering = ['sku', ]

    def __str__(self):
        return self.sku
    
    @property
    def quantityincart(self):
        orderproduct =  OrderProduct.objects \
            .filter(order=Order.objects.filter(submitted=None).filter(user=get_current_user()).first()) \
            .filter(product_id=self.id).values('quantity', 'id').first()
        return orderproduct


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT)
    notes = models.CharField(max_length=255, blank=True, null=True)
    submitted = models.DateTimeField(null=True, blank=True, default=None)
    processed = models.DateTimeField(null=True, blank=True, default=None)
    objects = models.Manager()

    def __str__(self):
        return f'Order # is {self.id}'

    @property
    def total(self):
        return sum(orderproduct.amount for orderproduct in OrderProduct.objects.filter(order=self))
    
    @classmethod
    def pre_save(cls, sender, instance, *args, **kwargs):
        if not instance.pk:
            instance.user = get_current_user()
pre_save.connect(Order.pre_save, sender=Order)


class OrderProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.RESTRICT)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    quantity = models.SmallIntegerField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Product is {self.product.sku} and quantities are {self.quantity}'

    @property
    def amount(self):
        return self.quantity*self.price

    def createupdate(product, quantity):
        order = Order.objects.filter(submitted=None).filter(user=get_current_user()).first()
        if not order:
            order = Order.objects.create()
        orderproduct = OrderProduct.objects.filter(order=order).filter(product=product).first()
        if orderproduct:
            orderproduct.quantity = int(quantity)
            orderproduct.save()
        else:
            orderproduct = OrderProduct.objects.create(
                product=product,
                price=product.price,
                quantity=quantity,
                order=order,
            )
        return orderproduct
    
    def objectdelete(orderproductid):
        OrderProduct.objects.filter(id=orderproductid).delete()
    
    @classmethod
    def pre_save(cls, sender, instance, *args, **kwargs):
        if not instance.pk:
            order = Order.objects.filter(submitted=None).filter(user=get_current_user()).first()
            if not order:
                order = Order.objects.create()
            instance.order = order
pre_save.connect(OrderProduct.pre_save, sender=OrderProduct)

application/forms.py
from django import forms
from application.models import Order


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ('notes', )
        widgets = {
            'notes': forms.Textarea(attrs={'placeholder': 'Notes', 'style': 'height: 100px;'}),
        }

application/views.py
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic.base import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from application.forms import OrderForm
from application.models import Device, Order, OrderProduct, Product


class DeviceListView(ListView):
    model = Device

    def get_queryset(self):
        return super().get_queryset().filter(active=1).order_by('brand__isnotpopular', 'brand__name', 'name')


class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        return super().get_queryset().filter(device_id=self.kwargs['device_id'], stock__gt=0)


@login_required
def OrderProductCreateUpdate(request, productid):
    product = Product.objects.get(pk=productid)
    quantity = request.POST['product_id_'+productid]
    orderproduct = OrderProduct.createupdate(product, quantity)
    context = {
        'product': product,
        'orderproduct': orderproduct,
    }
    return render(request, 'application/deletebutton.html', context)


@login_required
def OrderProductDelete(request, orderproductid):
    OrderProduct.objectdelete(orderproductid)
    return HttpResponse('In Cart: 0')


class OrderFormView(LoginRequiredMixin, FormView):
    form_class = OrderForm
    template_name = 'application/orderproduct_list.html'

    def get_context_data(self, **kwargs):
        _context_data = super().get_context_data(**kwargs)
        _getobjectts = "OrderProduct.objects.filter(order=Order.objects.filter(submitted=None).filter(user=self.request.user).first())"
        _context_data['object_list'] = eval(_getobjectts)
        _context_data['total'] = '{:.2f}'.format(sum(float(object.amount) for object in eval(_getobjectts)))
        return _context_data
    
    def form_valid(self, form):
        order = Order.objects.filter(submitted=None).filter(user=self.request.user).first()
        order.notes = form.cleaned_data['notes']
        order.submitted = datetime.now()
        order.save()
        self.success_url = reverse('application:OrderSubmitted', kwargs={'order_id': order.id})
        return super().form_valid(form)


def OrderSubmitted(request, order_id):
    return render(request, 'application/submitted.html', {'order_id': order_id})


class OrderProductDeleteView(LoginRequiredMixin, View):
    def get(self, request, product_id):
       object = OrderProduct.objects.get(id=product_id)
       object.delete()
       return redirect(reverse('application:OrderFormView'))


class OrdersListView(LoginRequiredMixin, ListView):
    model = Order

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user).order_by('-pk')


class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        _context_data = super().get_context_data(**kwargs)
        _getobjectts = "OrderProduct.objects.filter(order_id=self.kwargs['pk'])"
        _context_data['object_list'] = eval(_getobjectts)
        _context_data['total'] = '{:.2f}'.format(sum(float(object.amount) for object in eval(_getobjectts)))
        return _context_data

application/templates/application/deletebutton.html
<button class="btn btn-sm btn-outline-danger" type="button" tabindex="-1"
id="button_product_id_{{product.id}}"
hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
hx-post="{% url 'application:OrderProductDelete' orderproductid=orderproduct.id %}"
hx-target="#incart_product_id_{{product.id}}"
hx-on=
"
htmx:afterRequest:
    $(this).prop('disabled', true);
    $(this).attr('hx-headers', '');
    $(this).attr('hx-post', '');
    $(this).attr('hx-target', '');
    $('#product_id_{{product.id}}').focus();
">
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
</svg>
</button>

application/templates/application/device_list.html
{% extends 'base.html' %}
{% block content %}
{% regroup object_list by brand as grouped %}
{% for group in grouped %}
    {% for object in group.list %}
        {% ifchanged %}
            <br>
            <span class="fs-1 text-coral">{{ object.brand }}</span>
        {% endifchanged %}
        {% if forloop.first or forloop.counter0|divisibleby:4 %}
            <div class="row row-cols-1 row-cols-sm-2 row-cols-xl-4">
        {% endif %}
        <div class="col">
            <a href="{% url 'application:ProductListView' device_id=object.id %}"
                class="text-decoration-none">{{ object.name }}
            </a>
        </div>
        {% if forloop.counter|divisibleby:4 or forloop.last %}</div>{% endif %}
        {% ifchanged %}
            <br>
        {% endifchanged %}
    {% endfor %}
{% endfor %}
<br>
{% endblock content %}

application/templates/application/orderproduct_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% if total and object_list.first %}
    <form method="post">{% csrf_token %}
        <div class="container">
            {{ form|crispy }}
            <br>
            <div class="container-fluid">
                <div class="row row-cols-1 row-cols-sm-1 row-cols-xl-3">
                    <div class="col">
                        <span class="text-info fs-3">Order # {{ object_list.first.order.id }}</span>
                    </div>
                    <div class="col text-center">
                        <div class="d-grid col-8 mx-auto">
                        <button type="submit" class="btn btn-warning" autofocus>Submit Cart</button>
                    </div>
                </div>
                <div class="col text-end">
                    <span class="text-info fs-3">Total : {{ total }}</span>
                </div>
            </div>
        </div>
    </form>
{% endif %}
<div class="d-flex justify-content-center">
    <!-- text-light table-bordered border-secondary -->
    <table class="table">
        <tr>
            <th style="width: 5%;"></th>
            <th class="fs-5" style="width: 15%;">Product SKU</th>
            <th class="fs-5">Product Title</th>
            <th class="text-end fs-5" style="width: 6%;">Stock</th>
            <th class="text-end fs-5" style="width: 6%;">Quantity</th>
            <th class="text-end fs-5" style="width: 7%;">Price</th>
            <th class="text-end fs-5" style="width: 8%;">Amount</th>
            <th style="width: 5%;"></th>
        </tr>
        {% for object in object_list %}
            {% if object.quantity > object.product.stock %}
                <tr class="text-light bg-secondary">
            {% else %}
                <tr>
            {% endif %}
                <td class="text-center"><img src="{{ object.product.image.url }}" width="50"></td>
                <td class="fs-6">{{ object.product.sku }}</td>
                <td class="fs-6">{{ object.product.title }}</td>
                <td class="text-end fs-6">{{ object.product.stock }}</td>
                <td class="text-warning text-end fs-6">
                    <!-- <input class="form-control form-control-sm text-end"
                    type="number" min="1" max="{{ object.stock }}" step="1"
                    placeholder="Enter Quantity" style="width: 100px;"
                    name="product_id_{{object.id}}" id="product_id_{{object.id}}"
                    hx-trigger="keyup[keyCode==13]"
                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                    hx-post="{% url 'application:OrderProductCreateUpdate' productid=object.id %}"
                    hx-swap="outerHTML"
                    hx-include="[name='product_id_{{object.id}}']" 
                    hx-target="#button_product_id_{{object.id}}" 
                    onkeypress="return event.charCode >= 48 && event.charCode <=57"
                    value="{{ object.quantity }}"> -->
                    {{ object.quantity }}
                </td>
                <!-- hx-on=
                "htmx:afterRequest:
                    $('#incart_product_id_{{object.id}}').text((this.value=='') ? 'In Cart: 0' : 'In Cart: ' + this.value);
                    this.value='';
                    " -->
                <td class="text-secondary text-end fs-6">{{ object.price }}</td>
                <td class="text-end fs-6">{{ object.amount }}</td>
                <td class="text-danger text-center fs-6">
                    <a href="{% url 'application:OrderProductDeleteView' product_id=object.id %}" class="btn btn-sm btn-danger">Delete</a>
                    <!-- <button class="btn btn-sm btn-outline-danger" type="button" tabindex="-1"
                        id="button_product_id_{{object.id}}"
                        hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                        hx-post="{% url 'application:OrderProductDelete' orderproductid=object.id %}"
                        >
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                        </svg>
                    </button> -->
                    <!-- hx-target="#incart_product_id_{{object.id}}"
                    hx-on=
                    "
                    htmx:afterRequest:
                        $(this).prop('disabled', true);
                        $(this).attr('hx-headers', '');
                        $(this).attr('hx-post', '');
                        $(this).attr('hx-target', '');
                        
                        $('#product_id_{{object.id}}').focus();
                    "> -->
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="8" class="text-center fs-3 text-warning">No Products found in the cart.</td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock content %}

application/templates/application/product.html
<div class="d-flex justify-content-center">
    <div class="text-center">
        <table>
            <tr>
                {% if object.image %}
                    <td><img src="{{ object.image.url }}" alt="Hello World" height="300px"></td>
                {% else %}
                    {% load static %}
                    <td><img src="{% static '/images/image-error.jpg' %}" alt="Hello World" height="300px"></td>
                {% endif %}
            </tr>
            <tr>
                <td class="text-warning">{{ object.sku }}</td>
            </tr>
            <!-- <tr>
                <td class="text-secondary">{{ object.title }}</td>
            </tr> -->
            {% if user.is_authenticated %}
                <tr>
                    <td class="text-info">
                        Stock : {{ object.stock }},
                        Price : ${{ object.price }}
                    </td>
                </tr>
                <tr>
                    <td>
                        {% if object.quantityincart.id %}
                            <span id="incart_product_id_{{object.id}}">In Cart: {{ object.quantityincart.quantity }}</span>
                            <button class="btn btn-sm btn-outline-danger" type="button" tabindex="-1"
                                id="button_product_id_{{object.id}}"
                                hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                                hx-post="{% url 'application:OrderProductDelete' orderproductid=object.quantityincart.id %}"
                                hx-target="#incart_product_id_{{object.id}}"
                                hx-on=
                                "
                                htmx:afterRequest:
                                    $(this).prop('disabled', true);
                                    $(this).attr('hx-headers', '');
                                    $(this).attr('hx-post', '');
                                    $(this).attr('hx-target', '');
                                    
                                    $('#product_id_{{object.id}}').focus();
                                ">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                                </svg>
                            </button>
                        {% else %}
                            <span id="incart_product_id_{{object.id}}">In Cart: 0</span>
                            <button class="btn btn-sm btn-outline-danger" type="button" tabindex="-1"
                                id="button_product_id_{{object.id}}"
                                hx-headers=''
                                hx-post=""
                                hx-target="#incart_product_id_{{object.id}}"
                                hx-on=
                                "htmx:afterRequest:
                                    $(this).prop('disabled', true);
                                    $(this).attr('hx-headers', '');
                                    $(this).attr('hx-post', '');
                                    $(this).attr('hx-target', '');
                                    $('#product_id_{{object.id}}').focus();
                                " disabled>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                                </svg>
                            </button>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td><center>
                        <div class="input-group mb-3 pt-2" style="width: 200px;">
                            <input class="form-control form-control-sm"
                                placeholder="Enter Quantity"
                                type="number" min="1" max="{{ object.stock }}" step="1"
                                name="product_id_{{object.id}}" id="product_id_{{object.id}}"
                                hx-trigger="keyup[keyCode==13]"
                                hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                                hx-post="{% url 'application:OrderProductCreateUpdate' productid=object.id %}"
                                hx-include="[name='product_id_{{object.id}}']"
                                hx-swap="outerHTML"
                                hx-target="#button_product_id_{{object.id}}" 
                                hx-on=
                                "htmx:afterRequest:
                                    $('#incart_product_id_{{object.id}}').text((this.value=='') ? 'In Cart: 0' : 'In Cart: ' + this.value);
                                    this.value='';
                                "
                                onkeypress="return event.charCode >= 48 && event.charCode <=57"
                                {% if forloop.first %} autofocus {% endif %}
                            >
                            <button class="btn btn-sm btn-outline-success" type="button" tabindex="-1"
                                name="abutton_product_id_{{object.id}}" id="abutton_product_id_{{object.id}}"
                                hx-trigger="click"
                                hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                                hx-post="{% url 'application:OrderProductCreateUpdate' productid=object.id %}"
                                hx-include="[name='product_id_{{object.id}}']"
                                hx-swap="outerHTML"
                                hx-target="#button_product_id_{{object.id}}" 
                                hx-on=
                                "htmx:afterRequest:
                                    $('#incart_product_id_{{object.id}}').text($('#product_id_{{object.id}}').val()=='' ? 'In Cart: 0' : 'In Cart: ' + $('#product_id_{{object.id}}').val());
                                    $('#product_id_{{object.id}}').val('');
                                    $('#product_id_{{object.id}}').focus();
                            "
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus" viewBox="0 0 16 16">
                                    <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z"/>
                                    <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                                </svg>
                            </button>
                        </div>
                    </center></td>
                </tr>
            {% endif %}
        </table>
        <br>
    </div>
</div>

application/templates/application/product_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    {% for object in object_list %}
        {% if forloop.first %}
            <center><p class="text-primary fs-1">{{ object.device }}</p></center>
        {% endif %}
        {% if forloop.first or forloop.counter0|divisibleby:4 %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-xl-4">
        {% endif %}
            <div class="col">
                {% include 'application/product.html' %}
            </div>
        {% if forloop.counter|divisibleby:4 or forloop.last %}</div>{% endif %}
    {% endfor %}
</div>
{% endblock content %}

application/templates/application/submitted.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row row-cols-1 row-cols-sm-1 row-cols-xl-1">
        <div class="col text-center">
            <span class="text-info fs-1">Order # {{order_id}} is successfully Submitted.</span>
        </div>
    </div>
</div>
{% endblock content %}